###################################
#             Items: Options
# Item: <ID:MD/Item Name> - You can choose the item with its id and meta data.
# Amount: <Number> - Choose how many of the item you get.
# Name: <Name> - The display name that goes on the item.
# Lore: <Line 1>,<Line 2>,<Line 3>,<Line 4> - The lore that will go under the enchantments. Split lines with a ','
# <Enchantment>:<Level> - Choose the enchantment you want to add to the item. You can use the in-game names of the enchantment if you want. Replace the spaces in the name with a "_".
###########################################################
#                    Sound Options                        #
# 1.9 and up players use these sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
###################################################################
#                         Firework Colors:                        #
#      Aqua, Black, Blue, Fuchsia, Gray, Green, Lime, Maroon,     #
#  Navy, Olive, Orange, Purple, Red, Silver, Teal, White, Yellow  #
###################################################################
Settings: #Settings - Hex Color support does work, Please use #FFFFFF format!
  Prefix: '&7[&6Vouchers&7]: ' #The prefix before messages.
  Updater: true
Vouchers: #Where you make your vouchers.
  Money: #The name of the voucher.
    Item: 'PAPER' #The item the voucher is.
    Name: '&8&l>&7&l>&aMoney Voucher&7&l<&8&l<' #The item name.
    Lore: #The item's lore
      - '&7Use this voucher to gain &a$%Arg%&7.'
      - '&7&l(&6&l!&7&l) &7Right click to redeem.'
    Player: '' #Set the Item: to PLAYER_HEAD and use this to set the skin on the player head. Can use Name/Hash/URL
    Glowing: false #Toggle if the item will have a glowing effect or not.
    Commands: #The commands that are run when redeemed.
      - 'eco give %Player% %Arg%'
    Options: #The options
      Message: '&7You have just earned $%Arg%.' #The message sent to the player when redeemed. Set to '' if no message needs to be sent.
      Whitelist-Worlds: #This allows you to make it so some vouchers can only be used in specific worlds.
        Toggle: false #True if you wish to use this feature.
        Message: '&cYou can not use that voucher here as you are not in a whitelisted world for this voucher.' #The message sent to the user that tried to use it in a non whitelisted world.
        Worlds: #List of worlds you want the voucher to be used in.
          - 'world'
      Permission: #Permission options.
        Whitelist-Permission: #The player needs this permission to use it.
          Toggle: false #Toggle the permission on or off.
          Message: '&cYou do not have permission to use that voucher.'
          Permissions: #List of permissions the player needs.
            - 'voucher.money'
        Blacklist-Permissions: #If the player has any of these permissions then they can't use the voucher.
          Toggle: false #Toggle if it checks for blacklisted permissions.
          Message: '&cYou have a blacklisted permission and can''t use this voucher.' #The message that is sent to the player if they have a blacklisted message. Use %permission% if you wise to show the permission they need.
          Permissions: #List all the blacklisted permissions here.
            - 'voucher.blacklist.money'
      Limiter: #Limiter options.
        Toggle: false #Toggle on or off the limiter.
        Limit: 10 #The limit of how many times it may be used.
      Two-Step-Authentication: #This is for when the player right-clicks the voucher. It tells them to click again to confirm.
        Toggle: false #Toggle this option on or off.
      Sound: #The sound options.
        Toggle: true #Toggle on or off if a sound is played.
        Sounds: #The sound that is played. Make sure the sound works with your minecraft version.
          - 'CLICK'
      Firework: #The firework options
        Toggle: true #Toggle if the firework goes off.
        Colors: 'Green, Lime' #The colors of the firework.
  RankUp:
    Item: 'REDSTONE'
    Name: '&8&l>&7&l>&c%Arg% Voucher&7&l<&8&l<'
    Lore:
      - '&7Use this voucher to rank up to &c%Arg%&7.'
      - '&7&l(&6&l!&7&l) &7Right click to redeem.'
    Player: ''
    Glowing: false
    Commands:
      - 'pex user %Player% group set %Arg%'
    Options:
      Message: '&7Congratulations, you have just ranked up to &6%Arg%&7.'
      Whitelist-Worlds:
        Toggle: false
        Message: '&cYou can not use that voucher here as you are not in a whitelisted world for this voucher.'
        Worlds:
          - 'world'
      Permission:
        Whitelist-Permission:
          Toggle: false
          Permissions:
            - 'voucher.rankup'
        Blacklist-Permissions:
          Toggle: false
          Message: '&cYou already have this rank and can''t use this voucher.'
          Permissions:
            - 'voucher.blacklist.rankup'
      Limiter:
        Toggle: false
        Limit: 10
      Two-Step-Authentication:
        Toggle: false
      Sound:
        Toggle: true
        Sounds:
          - 'CLICK'
      Firework:
        Toggle: true
        Colors: 'Black, Gray, Red'
  GSet:
    Item: 'DIAMOND'
    Name: '&8&l>&7&l>&bGod-Set Voucher&7&l<&8&l<'
    Lore:
      - '&7Use this voucher to get a god set.'
      - '&7&l(&6&l!&7&l) &7Right click to redeem.'
    Player: ''
    Glowing: true
    Items:
      - 'Item:DIAMOND_HELMET, Amount:1, Name:&bGod Helmet, Protection:4, Respiration:1, Aqua_Affinity:3, Unbreaking:3, Thorns:3'
      - 'Item:DIAMOND_CHESTPLATE, Amount:1, Name:&bGod Chestplate, Protection:4, Unbreaking:3, Thorns:3'
      - 'Item:DIAMOND_LEGGINGS, Amount:1, Name:&bGod Leggings, Protection:4, Unbreaking:3, Thorns:3'
      - 'Item:DIAMOND_BOOTS, Amount:1, Name:&bGod Boots, Protection:4, Depth_Strider:3, Unbreaking:3, Thorns:3'
    Options:
      Message: '&7Congratulations, you have your self a new God-Set.'
      Whitelist-Worlds:
        Toggle: false
        Message: '&cYou can not use that voucher here as you are not in a whitelisted world for this voucher.'
        Worlds:
          - 'world'
      Permission:
        Whitelist-Permission:
          Toggle: false
          Permissions:
            - 'voucher.gset'
        Blacklist-Permissions:
          Toggle: false
          Message: '&cYou have a blacklisted permission and can''t use this voucher.'
          Permissions:
            - 'voucher.blacklist.gset'
      Limiter:
        Toggle: false
        Limit: 10
      Two-Step-Authentication:
        Toggle: false
      Sound:
        Toggle: true
        Sounds:
          - 'CLICK'
      Firework:
        Toggle: true
        Colors: 'Black, Gray, Aqua'
  Random_1:
    Item: 'SUNFLOWER'
    Name: '&8&l>&7&l>&cRandom Voucher &6&l#1&7&l<&8&l<'
    Lore:
      - '&7Win a random prize.'
      - ''
      - '&6&l#1: &a$100'
      - '&6&l#2: &a$1,000'
      - '&6&l#3: &a$10,000'
      - '&6&l#4: &a$100,000'
      - '&6&l#5: &a$1,000,000'
      - ''
      - '&7&l(&6&l!&7&l) &7Right click to redeem.'
    Player: ''
    Glowing: false
    Random-Commands: #Picks a random prize. There is no chance system for this only a random prize.
      - 'eco give %Player% 100'
      - 'eco give %Player% 1000'
      - 'eco give %Player% 10000'
      - 'eco give %Player% 100000'
      - 'eco give %Player% 1000000'
    Options:
      Firework:
        Toggle: true
        Colors: 'Black, Green'
  Random_2:
    Item: 'SUNFLOWER'
    Name: '&8&l>&7&l>&cRandom Voucher &6&l#2&7&l<&8&l<'
    Lore:
      - '&7You feeling lucky?'
      - ''
      - '&6&l#1: &a$100 &c45%'
      - '&6&l#2: &a$1,000 &c25%'
      - '&6&l#3: &a$10,000 &c15%'
      - '&6&l#4: &a$100,000 &c10%'
      - '&6&l#5: &a$1,000,000 &c5%'
      - ''
      - '&7&l(&6&l!&7&l) &7Right click to redeem.'
    Player: ''
    Glowing: false
    #Chance Command Layout: - '<Chance> <Command goes after>'
    Chance-Commands: #Picks a prizes based on a chance system. Chance-System wiki: https://github.com/badbones69/Vouchers/wiki/Chance-System-Wiki
      - '45 eco give %Player% 100'
      - '25 eco give %Player% 1000'
      - '15 eco give %Player% 10000'
      - '10 eco give %Player% 100000'
      - '5 eco give %Player% 1000000'
    Options:
      Firework:
        Toggle: true
        Colors: 'Black, Green'